### ISSUE TITLE
Multiple components in the same file

### ISSUE THREAD

**Issue by lucasconstantino** [storybooks/babel-plugin-react-docgen#14]
It appears to be a bug, but when I have multiple components on the same file, the docgen info is not beeing attached to the component's class.

I'll try and investigate further.

**Comment by arunoda** [comment]
Actually,  that how docgen works. 
They only works when you have a single component in the file.

**Comment by arunoda** [comment]
@madushan1000 BTW react-docgen [supports](https://github.com/reactjs/react-docgen/blob/1f3cac2f4cbf1b45a0c657817b273dd8c54a8309/src/resolver/__tests__/findExportedComponentDefinition-test.js#L207) multiple classes if it only export a single class.
Do we cover that case?

**Comment by lucasconstantino** [comment]
I notice this issue when having two stateless components, only one of them being exported, and this one being exported as the default.

```js
import React, { PropTypes } from 'react'

const Second = () => (
  <div>Sample</div>
)

const First = ({ children }) => (
  <div>
    { children }
    <Second />
  </div>
)

First.propTypes = {
  children: PropTypes.node
}

export default First
```

I think this is indeed a missing functionality, but by far it is not the most relevant one. I guess adding it to the README might be fine for most users. I'll see if this happens with other situations as well.

Thanks for the quite reply! I'll leave it open for you guys to decide how to proceed ;)

**Comment by arunoda** [comment]
I think we should only add docs for the default export. (Which is `First` in this case).
If that's not, we should fix it.
@madushan1000 check about this, when you have some time.

Of course, we need to mention this on the README.

**Comment by madushan1000** [comment]
There should be a way to see if a class if exported or not. I'll take a look.

**Comment by danielduan** [comment]
I think this issue has been fixed already. Leave a comment if it hasn't been.

**Comment by CLL80** [comment]
I see that when exporting multiple components from a single file. Docs aren't rendered at all—even for the `default` exported component. Based on the comments above, it seems the expected behavior would be that docs are rendered the default export only, but no docs are rendered.

This can be tested by exporting a component in addition to the default export. For example, in `test/fixtures/case5/actual.js:

```js
import React, { PropTypes } from 'react'

export const Second = () => (
  <div>Sample</div>
)

const First = ({ children }) => (
  <div>
    { children }
    <Second />
  </div>
)

First.propTypes = {
  children: PropTypes.node
}

export default First
```
Note the `export const Second`

In this case, `First.__docgenInfo` does not exist.
