### ISSUE TITLE
Use the React stateless class detector used in react-docgen

### ISSUE THREAD

**Issue by arunoda** [storybooks/babel-plugin-react-docgen#16]
React Docgen has it's own way to detecting React stateless classes. So it's better to use that.
It's located in: https://github.com/reactjs/react-docgen/blob/master/src/utils/isStatelessComponent.js

We can get it directly with:

``` js
import isStatelessComponent from 'react-docgen/dist/utils/isStatelessComponent'
```

**Comment by arunoda** [comment]
@madushan1000 check this out.

**Comment by madushan1000** [comment]
I tried using it before. But react-docgen uses recast as the AST walker. And recast doesn't seem to support babel6 ASTs. SO we can't use those functions. 
But it looks like there are some options(https://babeljs.io/blog/2016/09/28/6.16.0) we can pass to the parser so it generates recast compatible ASTs. I'll try it today.

**Comment by madushan1000** [comment]
So, using babel parser and generator options we can use recast for both instead of babylon in bable6. But I think it's overkill for just one plugin.

**Comment by arunoda** [comment]
Okay. Let's leave it like this for now.

**Comment by danielduan** [comment]
for context, docgen moved over to babylon but their `isStatelessComponent` isn't on parity with ours so there's no point moving over.
