### ISSUE TITLE
Support for resolvers and handlers

### ISSUE THREAD

**Issue by probablyup** [storybooks/babel-plugin-react-docgen#22]
`react-docgen` proper [allows for custom functions](https://github.com/reactjs/react-docgen#parsesource--resolver--handlers) that modify or enhance the default output.

This is super useful for detecting things like spread applying multiple prop type trees, etc since docgen doesn't handle that natively.

**Comment by arunoda** [comment]
Yeah. We could add that support.
Send us a PR.

**Comment by danielduan** [comment]
support for resolver has been published. keeping this issue open for handlers.

**Comment by carrickjason** [comment]
@danielduan Why are handler unnecessary?

**Comment by danielduan** [comment]
@carrickjason I haven't seen any demand for that feature. If you'd like to take a shot at creating a PR to add support for custom resolvers, I'd be more than happy to take a look and get it merged.

**Comment by Bobgy** [comment]
Hi, I want to use https://github.com/siddharthkp/react-docgen-external-proptypes-handler with @storybook/addon-info which uses babel-plugin-react-docgen. So I need to be able to use handlers here.
Not familiar with any of things here, so I couldn't help with PR or anything, just stating how it could be useful.
