### ISSUE TITLE
Support generate doc with imported component

### ISSUE THREAD

**Issue by Stupidism** [storybooks/babel-plugin-react-docgen#28]
A member of them said this is possible in this [issue](https://github.com/reactjs/react-docgen/issues/185#issuecomment-302544343) 
reference doc is [here](https://github.com/reactjs/react-docgen#parsesource--resolver--handlers)

**Comment by danielduan** [comment]
I'm not sure what you're asking for here. With this plugin configured with babel, when you access a component via the import or require, you should be able to see the docgen info.

```
const Component = require('./component.jsx');
console.log(Component.__docgenInfo);
```

**Comment by Stupidism** [comment]
```
// Button.js
Button.propTypes = {
  /*
   *  callback when button is clicked
   */
  onClick: PropTypes.func,
}

export default Button;

// ButtonWithColor.js
import Button from './Button';
export withColor(Button);
```

Then the description info is lost.
```
const ButtonWithColor = require('./ButtonWithColor');
console.log(ButtonWithColor.__docgenInfo);
```

**Comment by danielduan** [comment]
There's no way around this unfortunately. `react-docgen` only supports getting proptype info from the component file itself, not any imported components or proptypes.

I think its a limitation of `react-docgen` itself, but if you find a solution, please open a PR. I would love to see that implemented.

**Comment by Stupidism** [comment]
@danielduan But [here](https://github.com/reactjs/react-docgen/releases/tag/v2.11.0) it says hoc is OK.

>Detect exported components passed to HOCs
>Until now, react-docgen didn’t find components that are passed to a higher order component (HOC):
```
function MyComponent() { /* ... */ }
export default hoc(MyComponent);
```
>The workaround was to change the resolver to find all component definitions in the file, something that is not always desirable.
>With #124, @ rtsao extended the default resolver to be able to handle these cases.

**Comment by danielduan** [comment]
I think their case is when the HOC is in the same file.

Their tests are all contained in the same file:
https://github.com/reactjs/react-docgen/pull/124/files
