### ISSUE TITLE
`export default Component` and functional components declared with `function()` do not work

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [storybooks/babel-plugin-react-docgen#33]
I've been looking at this for two days without any progress so I thought I'd bring the problem here. Does anything jump out is invalid to you guys?

### Versions

react-docgen: 3.0.0-beta6
babel-plugin-react-docgen: 1.7.0

### Babelrc

```json
{
  "presets": [
    "react",
    "es2015"
  ],
  "plugins": [
    "react-docgen",
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-object-rest-spread",
    "transform-function-bind",
    "transform-runtime"
  ]
}
```

### Source

```jsx
import React from 'react';
import PropTypes from 'prop-types';
import { processProps } from '../utilities';

export default function Button(props) {
  return <button {...processProps(props)} />;
}

Button.propTypes = {
  /**
   * Breakpoint where button changes to block
   **/
  block: PropTypes.oneOf(['xs', 'sm', 'md', 'lg', true]),
  /**
   * Color class
   **/
  color: PropTypes.oneOf(['primary', 'secondary', 'tertiary']),
  /**
   * Size class
   **/
  size: PropTypes.oneOf(['baby', 'mama', 'papa']),
  /**
   * Add additional CTA specific styles -- Only applies to Button components
   */
  isCTA: PropTypes.bool,
  /**
   * The button's content
   */
  children: PropTypes.node
};

```

### Problem
Not getting `__docgenInfo` property on component constructor.
<img width="517" alt="screen shot 2017-08-13 at 10 51 58 am" src="https://user-images.githubusercontent.com/3114629/29250717-78100d96-8015-11e7-9457-ff0c8bba99b4.png">

**Comment by danielduan** [comment]
It looks like we might not support stateless functional components like `function Component() {}`. A workaround would be to write it as `Component() => {}`.

We haven't tested it with Docgen 3, but that's probably not the issue here.

**Comment by GeorgeTaveras1231** [comment]
@danielduan Thanks for the feedback. Per your suggestion, I tried a couple different approaches and found the following.

These work:

```jsx
const Button = () => { /*omitted*/ }
export default Button;
```

```jsx
class Button extends Component { /*omitted*/ }
export default Button;
```

These **don't** work:

```jsx
function Button { /*omitted*/ }
export default Button;
```

```jsx
export default class Button extends Component { /*omitted*/ }
```

Also, thanks for opening the door for a PR. I would do it but I don't have the time at this very moment. I wouldn't totally mind opening a PR to document more explicitly what syntax is valid for this plugin to kick in. I see there is an example on the README that conflicts with what I've found, I wouldn't mind updating that example.

**Comment by konsumer** [comment]
I am having a similar issue (see [here](https://github.com/storybooks/storybook/issues/1762) and [here](https://github.com/konsumer/storybook_issue_1762) for a demo.) I can make it work if I only export 1 interface (stateless function or not) but I like to export default + individual components. 

Maybe a simple detect-react-components strategy would help:

1. If only default or 1 exported function, that's the react component
2. If there is more than one exported function (default and/or other exports) try to annotate them all, I don't really mind if other non-react-component functions get annotated, maybe hide behind a flag to not be so greedy about matching functions

If this makes sense, I'll work on a PR.

**Comment by danielduan** [comment]
I think there's a few bugs here:
1. inlined export doesn't get detected `export default class Button`
2. named exports don't get docgen info when there's a default export
3. `function Button()` doesn't get recognized as stateless functional components

Your approach sounds good and will fix 2, but you might need to address 1 as well.

**Comment by konsumer** [comment]
Yeh, I see your point. Maybe 1 could be resolved with "extends React.Component?" check. I feel like a straight check for "of the things exported, if it's a function or extends React.Component, or is createReactClass" would, if not overly-greedy, hit all the targets. As I said, I don't really mind if too much is annotated, as it can just be ignored. Does this seem like a sensible approach?

**Comment by konsumer** [comment]
This all stems from my fondness of exporting everything (for unit-tests and storybooks) but making a default export that is the complete redux-connected component, as I use it my app. Most of my code looks like this, and I'd love to be able to get the doctext out:

```js
import React from 'react'
import { connect } from 'react-redux'
import PropTypes from 'prop-types'

/** A dumb component that says "hello" */
const Docs = ({name}) => (<div>Hello {name}</div>)

Docs.propTypes = {
  /** the name of the person to say "hello" to */
  name: PropTypes.string
}

Docs.defaultProps = {
  name: 'World'
}

export const mapStateToProps = state => ({
  name: state.name
})

export default connect(mapStateToProps)(Docs)
```

This makes it so I can unit-test my state-mappings, the Component (without redux) and write storybook stories for just the component, but it's also super-simple to use in my redux-enabled app.

**Comment by konsumer** [comment]
I made an issue (and patch) [here](https://github.com/reactjs/react-docgen/issues/213) that resolves this for my use-case. I suspect that I am probably missing some key detail, but if it gets in, it should resolve the issue.

**Comment by konsumer** [comment]
In CLI it seems to work fine with a different built-in resolver, but I don't see any way to add that config to babel-plugin-react-docgen, as it's used in storybook's webpack config.

`react-docgen --pretty --resolver findAllComponentDefinitions src/stories/Demo.js`:
```json
[
  {
    "description": "A dumb component that says \"hello\"",
    "methods": [],
    "props": {
      "name": {
        "type": {
          "name": "string"
        },
        "required": false,
        "description": "the name of the person to say \"hello\" to",
        "defaultValue": {
          "value": "'World'",
          "computed": false
        }
      }
    }
  }
]
```

If the default were `findAllComponentDefinitions`, or we were able to override the resolver with a config var, it would make it work for my use-case.

**Comment by danielduan** [comment]
We could expose it as an option for the babel plugin. I'm gonna guess there's probably a way to pass something to react-docgen to turn on findAllComponentDefinitions too.

Sorry I'm not too responsive this past week and I'm gonna be away for the next one as well. If you find a solution, please do update and open a PR.

**Comment by flipace** [comment]
@konsumer @danielduan i made a pr which allows you to use one of the builtin resolvers of react-docgen by passing options to the babel plugin.

I'm not sure how to write the tests for it however :(
