### ISSUE TITLE
1.8.0 throws a large amount of errors

### ISSUE THREAD

**Issue by thebuilder** [storybooks/babel-plugin-react-docgen#36]
Once i updated from 1.7.0, running Storybook with docgen would drown my terminal in traversel errors. Spend some time trying to figure out what was causing this, trying to set the different resolvers, etc.

Turns out the issue is the add `console.error` that logs everything.
https://github.com/storybooks/babel-plugin-react-docgen/blob/735a80bca397df11295952e13bdd36171a043f56/src/index.js#L150

Since `react-docgen` just throws errors whenever it tries to parse files without React components, and the babel plugin is applied to all files, i believe it should just accept this errors. Maybe add a `verbose` or `debug` option if it is actually useful to see the stack?

**Comment by danielduan** [comment]
Thanks for looking into this! @thebuilder 

If you'd like to open a PR for this, I'd very much appreciate it. I can get to it sometime tomorrow if not.

**Comment by danielduan** [comment]
published 1.8.1 to fix this

**Comment by thebuilder** [comment]
Cool! I'll update now. ok👌
