### ISSUE TITLE
Flow prop documentation breaks when class property functions with optional parameters are used

### ISSUE THREAD

**Issue by wafflepie** [storybooks/babel-plugin-react-docgen#42]
This piece of code renders `No propTypes defined!` in the info:
```
// @flow
import React from 'react'

type PropsType = {
  /** The text to be rendered in the button */
  label: number,
}

class FlowTypeButton extends React.Component<PropsType> {
  foo = (bar?: string) => {
    console.log(bar)
  }

  render() {
    return <button>{this.props.label}</button>
  }
}

export default FlowTypeButton
```

If I remove the question mark, the prop type description is rendered correctly:
```
foo = (bar: string) => {
```

property | propType | required | default | description
-- | -- | -- | -- | --
label | number | yes | - | The text to be rendered in the button

Tested on v1.8.2 of babel-plugin-react-docgen and reproduced in storybook of both v3.4.0-alpha.7 and v3.3.12.

**Comment by wafflepie** [comment]
This is solved by react-docgen@3.0.0, I managed to fix it temporarily by adding
```
  "resolutions": {
    "@storybook/react/**/react-docgen": "3.0.0-beta9"
  }
```
to my package.json.

**Comment by tkiethanom** [comment]
@wafflepie I tried doing the "resolutions" thing in my package.json. It doesn't seem to work. Do you reinstall the package after adding the resolutions to the package.json?

**Comment by Hypnosphi** [comment]
@tkiethanom it only works with yarn

**Comment by tkiethanom** [comment]
@Hypnosphi Thanks for the reply. Do you know of a good work around for regular old npm users? For right now I just pointed to this fork https://github.com/Khan/babel-plugin-react-docgen/tree/docgen-v3.

**Comment by wafflepie** [comment]
@tkiethanom Sorry for not replying earlier. I don't think there is an alternative for npm users which is not hacky. 😞

**Comment by danielduan** [comment]
I'm not particularly comfortable with publishing a release version that depends on a beta version but I don't think there are any better alternatives.

I'm gonna publish a new version that relies on the beta to fix most of these flow issues since that seems to be a growing problem.

**Comment by danielduan** [comment]
v1.9.0 published. clear your lock files, reinstall, and let me know if this doesn't fix the issue.
