### ISSUE TITLE
Named exports with declarations are ignored

### ISSUE THREAD

**Issue by lawliet29** [storybooks/babel-plugin-react-docgen#50]
Consider the following component:

```jsx
import React from 'react';
import PropTypes from 'prop-types';

export const Button = ({text, onClick}) => (
    <button onClick={onClick}>{text}</button>
);

Button.propTypes = {
    text: PropTypes.string,
    onClick: PropTypes.func
}
```

`babel-plugin-react-docgen` ignores such a declaration because `isExported` function looks specifically for `ExportNamedDeclaration` with a specifier, i.e. `export {Button}` or `export {Button as GlobalSpecifierButton}`.

Is this expected behavior?
I'm currently patching `babel-plugin-react-docgen` manually to work with named exports with declarations, so I could submit a pull request with a fix.

**Comment by wuweiweiwu** [comment]
Can you also try:

```
const Button = ({text, onClick}) => (
    <button onClick={onClick}>{text}</button>
);

Button.propTypes = {
    text: PropTypes.string,
    onClick: PropTypes.func
}

export Button
```

I think it might be because you're exporting an inline declaration so that proptypes are never applied.

**Comment by wuweiweiwu** [comment]
I see. Do you mind submitting a PR with a fix?

Thanks!

**Comment by Hypnosphi** [comment]
`export {Button}` should work though
