### ISSUE TITLE
Error: Cannot find module 'recast'

### ISSUE THREAD

**Issue by original001** [storybooks/babel-plugin-react-docgen#62]
npm -v 5.6-5.8
node -v 8.9.4

you have `recast` in devDependencies, but you are using this module in general file. In some case I don't get module on top of `node_modules` tree. and it doesn't exist in `node_modules` of `babel-plugin-react-docgen`. it only exist in `react-docgen` `node_modules`. Please, add recast in dependencies.

**Comment by togakangaroo** [comment]
I get this too

**Comment by wuweiweiwu** [comment]
The fix would be to move it from devDependencies to dependencies

**Comment by togakangaroo** [comment]
deleting all node_modules and storybook and reinstalling them and `npx` init'ing storybook worked for me to fix it...so maybe it's not on yall and just a result of the npm ecosystem getting absurdly complex lately?

I don't know...

**Comment by rally25rs** [comment]
It sometimes works depending on the hoisting of the package manager wand what other packages are installed, but relying on this hoisting is a bad practice and can lead to unexpected results.

This also breaks use of yarn Plug'n'Play, or if you use yarn's nohoist feature to prevent `recast` from being moved to `node_modules/recast`

**Comment by vjpr** [comment]
This is broken in pnpm too. It just needs to be added to dependencies.

**Comment by danielduan** [comment]
fixed in version 2.0.2
