### ISSUE TITLE
How to docgen for an npm package?

### ISSUE THREAD

**Issue by blorenz** [storybooks/babel-plugin-react-docgen#70]
I recently refactored my docs out of my npm UI package and made a separate repository for my docs. I am not seeing the `__docgenInfo` on the components and I believe that is because they are being imported from `node_modules` in the docs now.  Is there a configuration that I am missing to parse these components in `node_modules`?

**Comment by danielduan** [comment]
Packages usually come precompiled so they don’t run through Babel where they can be processed with this plugin. You could certainly add your node_modules folder to the list of includes in webpack and compile it again to get the docs but know that this will significantly increase your build time.
